### PR TITLE
do notation, monadic guard

### PR DESCRIPTION
**Pull request by Technologicat**
Here's an attempt at do-notation for Python. It seems none of the monad libraries currently provide that.

Example:

```python
from oslash import List, do, let, guard

r = lambda low, high: List.from_iterable(range(low, high))
out = do(let(z=r(1, 21)),               # let is "<-"
         let(x=lambda e: r(1, e.z+1)),  # uses env via "lambda e: ..."
         let(y=lambda e: r(e.x, e.z+1)),
         lambda e: guard(List, e.x*e.x + e.y*e.y == e.z*e.z),
         lambda e: List.unit((e.x, e.y, e.z)))
print(out)
```

The syntax is loosely modeled after ``letrec`` in [unpythonic](https://github.com/Technologicat/unpythonic), which in turn was inspired by [[1]](https://nvbn.github.io/2014/09/25/let-statement-in-python/) [[2]](https://stackoverflow.com/questions/12219465/is-there-a-python-equivalent-of-the-haskell-let) [[3]](http://sigusr2.net/more-about-let-in-python.html).

This is pure Python 3.4, implemented essentially as a code generator. The client code would look cleaner if this was a syntactic macro instead (using [MacroPy3](https://github.com/azazel75/macropy)), but this version makes do (no pun intended) with Python's builtin capabilities.

Comments welcome.

Also, I think [guard](https://en.wikibooks.org/wiki/Haskell/Alternative_and_MonadPlus#guard) is useful, especially with ``List``. Where should it go in OSlash?

### CODE REVIEW

**Comment by Technologicat** [comment]
FWIW, since posting this, I've added a MacroPy3-based do-notation to `unpythonic`. Since `unpythonic` is not really a monad library, it's currently hard-coded for the List monad (but this limitation is easily removed).

See the `forall` syntax transformer in [forall.py](https://github.com/Technologicat/unpythonic/blob/master/unpythonic/syntax/forall.py). It's much cleaner and much less hacky than what is possible without macros.

(For comparison, the same feature is implemented without macros in the badly named [amb.py](https://github.com/Technologicat/unpythonic/blob/master/unpythonic/amb.py), but the code in this PR already contains a clean minimal version of the relevant parts of that.)

If you're interested in the macro approach, it could be adapted here.

**Comment by sobolevn** [comment]
@Technologicat you might be interested in this issue: https://github.com/dry-python/returns/issues/392

We are working on **typed** do-notation in Python, and I would love to hear your ideas about it!

**Comment by dbrattli** [comment]
This is pure gold! Sorry for taking so long. Been lost in F# for a long time. Planning to merge this soon.

**Comment by dbrattli** [comment]
I'm closing this as the commits here have now been merged into master through https://github.com/dbrattli/OSlash/pull/19 since I didn't have write access to the PR. Again, thanks for your contribution to OSlash!

**Pull request closed without merging**
